---
title: "Extinction Law"
output:
  html_document:
    df_print: paged
---


Let's take a look at the extinction laws that we can use to de-redden the young stars in  Cep Ob3b.  The three main laws are the Reike & Labowsky 1985 law, the Cardelli, Clayton and Mathis, and [Allen et al. 2014](https://ui.adsabs.harvard.edu/#abs/2014ApJ...786..113A).  The Allen et al. 2014 law was derived from misclassified spectral types.

We will make use of the [reticulate](https://rstudio.github.io/reticulate/) package.  Note, we are defining the python engine in the R setup chunk. 

```{r setup, include=TRUE}
#devtools::install_github("rstudio/reticulate")
library(reticulate)
use_python("/anaconda3/bin/python")
library(readr)
library(dplyr)
library(ggplot2)
```

Let's quickly check which version of python we are using.  I shoud be usng 3.6.x.
```{python}
import sys as sys
print(sys.version)
```


## Using astroquery

We can instantiate a new Vizer query object using the astroquery package.  We will then perform a search for "Cep OB3b"

```{python}
from astroquery.vizier import Vizier

v = Vizier

v.ROW_LIMIT = -1

catalog_list = v.find_catalogs('Cep OB3b')

catalogs = v.get_catalogs(catalog_list.keys())

```

As can be seen from the above code chunk, first use the `find_catalgos()` function to perform the search, then we get the catalogs using the resulting output.  We can now print the resulting catalogs.

```{python}

print(catalogs)
```

The first catalog in this small list, 'J/ApJ/750/125/ysos', is from my 2012 paper.  If we want to use it with, say pandas, we could do the following

```{python}
import pandas as pd

data = catalogs['J/ApJ/750/125/ysos']
data = data.to_pandas()

#data.column.values

print(data.head())

print(data.columns.values)

```






